[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
clap = { version = "4.5", features = ["derive"] }
colorize = "0.1"
tokio = { version = "1.0", features = ["full"] }
dirs = "5.0"
