name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: boot
            asset_name: boot-linux-amd64
          - os: windows-latest
            artifact_name: boot.exe
            asset_name: boot-windows-amd64.exe
          - os: macos-latest
            artifact_name: boot
            asset_name: boot-macos-amd64

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: cargo build --release
    
    - name: Rename binary
      shell: bash
      run: |
        cd target/release
        cp ${{ matrix.artifact_name }} ${{ matrix.asset_name }}
    
    - name: Upload Release Asset
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: target/release/${{ matrix.asset_name }}

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Download Artifacts
      uses: actions/download-artifact@v2
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          boot-linux-amd64/boot-linux-amd64
          boot-windows-amd64.exe/boot-windows-amd64.exe
          boot-macos-amd64/boot-macos-amd64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
